spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  datasource:
    username: root
    password: spring123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_agile?useSSL=false
  freemarker:
    template-loader-path: classpath:/mail-templates/
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
# mailr
app:
  mail-from: noreply@taskagile.com
  token-secret-key: 60dKuW2Qpc3YkUoaa9i6qY5cyaGgQM8clfxpDGWS3sY
  real-time-server-url: /rt
#logging:
#  level:
#    com.taskagile: debug
#    org.springframework.security: debug
