spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    username: root
    password: spring123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/task_agile?useSSL=false
  freemarker:
    template-loader-path: classpath:/mail-templates/
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
# mailr
app:
  mail-from: noreply@taskagile.com
#logging:
#  level:
#    com.taskagile: debug
#    org.springframework.security: debug
